config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sections#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sections, only: %i[index show] do
    resources :products, only: %i[show] do
      resources :ratings, only: %i[index new create]
    end
  end
  resources :products, only: %i[index]
  resources :orders, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[show new create]
    resources :chatrooms, only: :show do
      resources :messages, only: %i[new create]
    end
  end
  resource :cart, only: %i[show edit update]
  get "cart/confirmation", to: "carts#confirmation", as: :cart_confirmation
  resources :order_items, only: %i[new create edit update destroy]
  get "contact", to: "contact#show", as: :contact
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_cart_navbar.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown mt-2 me-5">
    <a href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <h1 class="align-items-center"><i class="fa-solid fa-cart-shopping" style="color: #FF3130;"></i></h1>
      <p class="nav-cart"><%= @quantity %></p>
    </a>
    <ul class="dropdown-menu dropdown-cart" role="menu">
      <% if  @cart.order_items == [] %>
        <li class="text-center">
          <div class="lottie-class d-flex justify-content-center text-center pb-2">
            <lottie-player src="https://res.cloudinary.com/dyv1blw2a/raw/upload/v1688301650/43012-screaming-fear-face_yvgljg.json" background="transparent" speed="1"
            style="width: 45%; height: 45%;" loop autoplay></lottie-player>
          </div>
          <span class="text-center">Oupsssss...</span>
        </li>
        <li class="text-center pb-2"><span class="text-center">Looks like you cart is empty !</span></li>
        <li>
          <li class=" divider btn-cart m-2 text-center"><%= link_to 'Start Shopping', products_path, class: "btn-tag"%></li>
        </li>
      <% else %>
        <% @cart.order_items.each do |order_item| %>
          <li>
            <span class="item pb-2">
              <span class="item-left">
                <%= cl_image_tag order_item.product.photo.key, height: 50, width: 50, crop: :fill, :effect=>"improve:outdoor" %>
                <span class="item-info">
                  <span><%= order_item.product.title %> x <%= order_item.quantity %></span>
                  <span >Rs <%= order_item.total_price %></span>
                </span>
              </span>
            </>
          </li>
        <% end %>
        <li class=" divider btn-cart pt-2 m-2" style="text-align: center;">Total : Rs <%= number_with_delimiter(@cart.total_price.to_i, delimiter: "’") %></li>
        <li class=" divider btn-cart pt-2 m-2"><%= link_to 'Checkout', cart_path, class: "btn-tag"%></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if warning %>
  <div class="alert alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= warning %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
    <%# <div class="waves">
      <div class="wave" id="wave1"></div>
      <div class="wave" id="wave2"></div>
      <div class="wave" id="wave3"></div>
      <div class="wave" id="wave4"></div>
    </div> %>

    <ul class="social">
      <a class="menu__link" href="https://www.facebook.com/lewagonmauritius" target="_blank"><i class="fa-brands fa-facebook" style="color: #000000,font-size: 50px"></i></a>
      <a class="menu__link" href="https://twitter.com/Lewagonparis" target="_blank"><i class="fa-brands fa-twitter" style="color: #000000,font-size: 50px;"></i></a>
      <a class="menu__link" href="https://www.linkedin.com/school/le-wagon/" target="_blank"><i class="fa-brands fa-linkedin" style="color: #000000,font-size: 50px;"></i></a>
      <a class="menu__link" href="https://www.instagram.com/lewagonmauritius/" target="_blank"><i class="fa-brands fa-instagram" style="color: #000000,font-size: 50px;"></i></a>
      </ul>
    </ul>
    <ul class="menu">
      <li class="menu__item"><a class="menu__link" href="/">Home</a></li>
      <li class="menu__item"><a class="menu__link" href="/products">Products</a></li>
      <li class="menu__item"><a class="menu__link" href="/orders">My orders</a></li>
      <li class="menu__item"><a class="menu__link" href="/contact">Contact</a></li>

    </ul>
    <div class="copyright">
      <p>&copy;2023 Nou Ration Ltd | All Rights Reserved</p>
    </div>
  </footer>
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand me-4 ps-2" href="/">
      <%# <img src="	http://localhost:3000/assets/logo-5086acf903bfff68…63734ac6d56d7561154ca90d7487112011d7fee0e79cc.png" alt="logo"
        style="width: 80px;" class="ms-2 rounded-3"> %>
      <%= image_tag "logo.png", class: "ms-2 rounded-3", style: "width: 80px;" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mt-2 mt-lg-0">
        <li class="nav-item active me-3">
          <a class="nav-link" href="/">Home <span
              class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link" href="/products">Products</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link" href="/orders">My Orders</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link" href="/contact">Contact</a>
        </li>
      </ul>


      <form class="d-flex me-5">
        <%= form_with url: products_path, method: :get, class: "d-flex", html: { autocomplete: 'off' } do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Keyword",
                autocomplete: 'off'
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-warning form-button" %>
        <% end %>
      </form>

      <%= render "shared/cart_navbar" %>

      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown me-2 pe-2">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar", alt: "dropdown menu", style: "width: 60px;" %>
              <% else %>
              <%= image_tag "avatar.png", class: "avatar", alt: "dropdown menu", style: "width: 60px;" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", "/users/edit", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item pe-2">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

</nav>