config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sections#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sections, only: %i[index show] do
    resources :products, only: %i[show] do
      resources :ratings, only: %i[index new create]
    end
  end
  resources :products, only: %i[index]
  resources :orders, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[show new create]
    resources :chatrooms, only: :show do
      resources :messages, only: %i[new create]
    end
  end
  resource :cart, only: %i[show edit update]
  get "cart/confirmation", to: "carts#confirmation", as: :cart_confirmation
  resources :order_items, only: %i[new create edit update destroy]
  get "contact", to: "contact#show", as: :contact
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/section.rb
class Section < ApplicationRecord
  has_one_attached :photo
  has_one_attached :banner
  has_many :products
  validates :title, presence: true, uniqueness: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[show]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @sections = Section.includes([photo_attachment: :blob]).all.order(:title)
    search
  end

  def show
    @products = Product.includes([photo_attachment: :blob]).all.order(:title)
    search
    @tag_section = []
    @section.products.each do |product|
      product.tags.each do |tag|
        @tag_section << tag
      end
    end
    @tag_section
  end

  private

  # Si on veut rajouter update, create... :
  # def section_params
  #   params.require(:section).permit(:title, :photo)
  # end

  def set_section
    @section = Section.find(params[:id])
  end

  def search
    if params[:query].present?
      redirect_to products_path(query: params[:query]) and return
    end
  end
end

app/views/sections/index.html.erb
<div class="slider-wrapper">
  <div class="slider">
  <%= image_tag("slider1.jpg", class: "slider1-img") %>
  <%= image_tag("slider2.jpg", class: "slider2-img") %>
  <%= image_tag("slider3.jpg", class: "slider3-img") %>
    <div class="slider-nav">
      <a href="#slide-1"></a>
      <a href="#slide-2"></a>
      <a href="#slide-3"></a>
    </div>
  </div>
</div>

<div class="homepage">
  <div class="container py-5">
    <p class="pb-4 fs-2">WHAT WE OFFER ?</p>
    <h2>YOUR FAVORITE FOOD</h2>
    <div class="container">
      <div class="row align-items-center pb-5">
        <div class="col text-center homepg-lottie">
          <div class="lottie-class d-flex justify-content-center text-center pb-2">
            <lottie-player src="https://res.cloudinary.com/dyv1blw2a/raw/upload/v1688318990/easy-to-order_eozr7v.json" background="transparent" speed="1"
            style="width: 241px; height: 194px;" loop autoplay></lottie-player>
          </div>
          <h4>Easy to order</h4>
          <p>You only need a few steps in ordering food</p>
        </div>
        <div class="col text-center homepg-lottie">
          <div class="lottie-class d-flex justify-content-center text-center pb-2">
            <lottie-player src="https://res.cloudinary.com/dyv1blw2a/raw/upload/v1688318990/fastest-delivery_mabpnd.json" background="transparent" speed="1"
            style="width: 241px; height: 194px;" loop autoplay></lottie-player>
          </div>
          <h4>Fastest Delivery</h4>
          <p>Delivery that is always ontime even faster</p>
        </div>
        <div class="col text-center homepg-lottie">
          <div class="lottie-class d-flex justify-content-center text-center pb-2">
            <lottie-player src="https://res.cloudinary.com/dyv1blw2a/raw/upload/v1688318989/best-quality_xrk2tx.json" background="transparent" speed="1"
            style="width: 241px; height: 194px;" loop autoplay></lottie-player>
          </div>
          <h4>Best Quality</h4>
          <p>Not only fast. For us, quality is also number one</p>
        </div>
      </div>
    </div>
    <%# <%= image_tag("services.jpg", class: "services-img") %>
    <h1>CATEGORIES</h1>
    <div class="cards">
      <% @sections.each do |section| %>
        <%= link_to section_path(section), class:"text-decoration-none" do %>
        <div class="card">
            <%= cl_image_tag section.photo.key, crop: :fill,  class:"cards-img"%>
          <div class="card-body border-top border-secondary">
            <h6 class="card-title"><%= section.title %></h6>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/sections/show.html.erb
<ul class="breadcrumb">
  <li><a href="/"><i class="fa-solid fa-house"></i></a></li>
  <li><a href="/sections/<%= @section.id %>"><%= @section.title %></a></li>
</ul>
<% if @section.banner.attached? %>
  <div class="slider-wrapper">
    <div class="slider">
      <%= cl_image_tag @section.banner.key, crop: :fill,  class:"slider1-img"%>
    </div>
  </div>
<% end %>

<div class="homepage">
  <div class="container">
    <p class="fs-1"><%= @section.title %></p>
  </div>
</div>
<div class="row justify-content-center tag-list py-2">
  <% @tag_section.uniq.each do |tag| %>
    <a class="text-center btn-tag2" style="text-align: center" href="/products?query= <%= tag.name %>"><%= tag.name %></a>
  <% end %>
</div>
<div class="container">
  <div class="cards-products">
    <% @products.each do |product| %>
      <% if @section.id == product.section_id %>
        <%= link_to section_product_path(@section, product), class:"text-decoration-none" do %>
          <div class="card">
            <%= cl_image_tag product.photo.key, crop: :fill,  class:"cards-img"%>
            <div class="card-tags">
              <% product.tags.each do |tag| %>
                <h6><span><%= tag.name %></span></h6>
              <% end %>
            </div>
            <div class="card-body">
              <h6 class="card-title"><%= product.title %></h6>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>