config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sections#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sections, only: %i[index show] do
    resources :products, only: %i[show] do
      resources :ratings, only: %i[index new create]
    end
  end
  resources :products, only: %i[index]
  resources :orders, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[show new create]
    resources :chatrooms, only: :show do
      resources :messages, only: %i[new create]
    end
  end
  resource :cart, only: %i[show edit update]
  get "cart/confirmation", to: "carts#confirmation", as: :cart_confirmation
  resources :order_items, only: %i[new create edit update destroy]
  get "contact", to: "contact#show", as: :contact
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items
  has_one :chatroom, dependent: :destroy
  has_one :review, dependent: :destroy
  has_many :messages, through: :chatroom

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  def index
    @orders = Order.all.order(oder_number: :desc)
    orders_rating
    search
  end

  def show
    @chatroom = Chatroom.where(order_id: @order.id).first
    @message = Message.new
    search
    order_rating
    @review = @order.review
    @marker = [{
      lat: current_user.latitude,
      lng: current_user.longitude
    }]
  end

  def edit;
  end

  def update
    @order.is_delivered = true
    @order.save
    redirect_to order_path(@order)
  end

  def destroy
    @order.destroy
    redirect_to orders_path, status: :see_other
  end

  private

  def order_rating
    unless @order.review.nil?
      @total_rate = show_star_rating(@order.review.general_rating)
      @delivery_rate = show_star_rating(@order.review.delivery_rating)
    end
  end

  def orders_rating
    @total_rate = []
    @orders.each do |order|
      unless order.review.nil?
        @total_rate.append(show_star_rating(order.review.general_rating))
      else
        @total_rate.append([])
      end
    end
  end

  def total_rate
    show_star_rating(order.review.general_rating)
  end

  def show_star_rating(rating)
    zero_star_icon_name = "star"
    full_star_icon_name = "star_fill"
    half_star_icon_name = "star_lefthalf_fill"
    rating_round_point5 = (rating * 2).round / 2.0
    (1..5).map do |i|
      next(full_star_icon_name) if i <= rating_round_point5
      next(half_star_icon_name) if rating_round_point5 + 0.5 == i
      zero_star_icon_name
    end
  end

  def set_order
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: @order.id)
  end

  def order_params
    params.require(:order).permit(:oder_number, :total_price)
  end

  def search
    if params[:query].present?
      redirect_to products_path(query: params[:query]) and return
    end
  end
end

app/views/orders/index.html.erb
<ul class="breadcrumb">
  <li><a href="/"><i class="fa-solid fa-house"></i></a></li>
  <li><a href="/orders">Orders</a></li>
</ul>
<div class="homepage">
  <div class="container">
    <p class="fs-1">Orders</p>
  </div>
</div>

<% if current_user.is_admin? %>
  <div class="container">
    <div class="row gx-5 gy-0">
      <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
          <tr>
            <th scope="col">Order number</th>
            <th scope="col">Date</th>
            <th scope="col">Total Price</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
          </tr>
        </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td>
                  <div>
                    <p class="fw-normal mb-1"> #<%= link_to order.oder_number, order_path(order), class: "text-dark fw-normal mb-1"%></p>
                  </div>
                </td>
                <td>
                  <div>
                    <p class="text-muted mb-0"> <%= order.created_at.strftime("%d/%m/20%y") %> </p>
                  </div>
                </td>
                <td>
                  <div>
                    <p class="text-muted mb-0">Rs <%= number_with_delimiter(order.total_price.to_i, delimiter: "’") %> </p>
                  </div>
                </td>
                <td>
                  <% if order.is_delivered? %>
                    <span class="order-success">Delivered</span>
                  <% else %>
                    <span class="order-awaiting">On it's way</span>
                  <% end %>
                </td>
                <td>
                  <%= link_to order_path(order), class:"text-decoration-none" do %>
                    <h3><i class="fa-solid fa-eye"></i></h3>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
<% elsif current_user.orders == [] %>
  <div class="container">
    <div class="row gx-5 gy-0">
      <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
          <tr>
            <th scope="col">Order number</th>
            <th scope="col">Date</th>
            <th scope="col">Total Price</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
      </table>
      <p class="mt-4">No orders history</p>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row gx-5 gy-0">
      <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
          <tr>
            <th scope="col">Order number</th>
            <th scope="col">Date</th>
            <th scope="col">Total Price</th>
            <th scope="col">Status</th>
            <th scope="col">Review*</th>
            <th td class="td-eye-order" scope="col">Preview</th>
          </tr>
        </thead>
          <tbody>
            <% @orders.each_with_index do |order, index| %>
              <% if order.user_id == current_user.id %>
                <tr>
                  <td>
                    <div>
                      <p class="fw-normal mb-1"> #<%= link_to order.oder_number, order_path(order), class: "text-dark fw-normal mb-1"%></p>
                    </div>
                  </td>
                  <td>
                    <div>
                      <p class="text-muted mb-0"> <%= order.created_at.strftime("%d/%m/20%y") %> </p>
                    </div>
                  </td>
                  <td>
                    <div>
                      <p class="text-muted mb-0 order-price">Rs <%= number_with_delimiter(order.total_price.to_i, delimiter: "'") %> </p>
                    </div>
                  </td>
                  <td>
                    <% if order.is_delivered? %>
                      <span class="order-success">Delivered</span>
                    <% else %>
                      <span class="order-awaiting">On it's way</span>
                    <% end %>
                  </td>
                  <td style="font-size: 1.2rem;">
                    <% if order.is_delivered? %>
                      <% if order.review.nil? %>
                        <%= link_to new_order_review_path(order), class:"text-decoration-none ", data: { controller: 'turbo' } do %>
                          <h2 class="fs-6 btn-review-index">Review your order</i></h2>
                        <% end %>
                      <% else %>


                        <%= link_to order_review_path(order, order.review), class:"text-decoration-none ", data: { controller: 'turbo' } do %>
                          <% @total_rate[index].each do |star| %>
                            <% if star == "star_fill" %>
                              <i class="fa-solid fa-star" style="color: #ffde0a;"></i>
                            <% elsif star == "star_lefthalf_fill" %>
                              <i class="fa-solid fa-star-half-stroke" style="color: #ffde0a;"></i>
                            <% else star %>
                              <i class="fa-regular fa-star" style="color: #ffde0a;"></i>
                            <% end %>
                          <% end %>
                        <% end %>


                      <% end %>
                    <% end %>


                  </td>
                  <td class="td-eye-order">
                    <%= link_to order_path(order), class:"text-decoration-none" do %>
                      <h3><i class="fa-solid fa-eye"></i></h3>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
      </table>
    </div>
  <p class="mt-3 review-delivered">* Once your order is delivered, you will be able to review it.</p>
  </div>
<% end %>

app/views/orders/show.html.erb
<div class="row text-center">
  <div class="col-9">
    <ul class="breadcrumb">
      <li><a href="/"><i class="fa-solid fa-house"></i></a></li>
      <li><a href="/orders">Orders</a></li>
      <li><a href="/orders/<%= @order.id %>">Order#<%= @order.oder_number %></a></li>
    </ul>
  </div>
  <div class="col-3">
    <% if @order.is_delivered? %>
      <% if @order.review.nil? %>
        <%= link_to new_order_review_path(@order), class:"text-decoration-none ", data: { controller: 'turbo' } do %>
          <h2 class="fs-6 btn-review">Review your order</i></h2>
        <% end %>
      <% else %>
        <%= link_to order_review_path(@order, @review), class:"text-decoration-none ", data: { controller: 'turbo' } do %>
          <div class="pt-4 star-size">
            <% @total_rate.each do |star| %>
              <% if star == "star_fill" %>
                <i class="fa-solid fa-star" style="color: #ffde0a;"></i>
              <% elsif star == "star_lefthalf_fill" %>
                <i class="fa-solid fa-star-half-stroke" style="color: #ffde0a;"></i>
              <% else star %>
                <i class="fa-regular fa-star" style="color: #ffde0a;"></i>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="homepage">
  <div class="container p-0 pt-3">
    <p class="fs-2 mb-0 pb-0">Order #<%= @order.oder_number %></p>
  </div>
</div>
<% if @order.is_delivered? %>
  <div class="container">
    <div class="lottie-class d-flex justify-content-center text-center pb-2">
      <lottie-player src="https://res.cloudinary.com/dyv1blw2a/raw/upload/v1688299091/114216-product-delivered_p4wgif.json" background="transparent" speed="1"
      style="width: 55%; height: 55%;" loop autoplay></lottie-player>
    </div>
    <div class="row">
      <div class="col-6">
        <p class="mb-5">Your order was delivered on the <%= @order.updated_at.strftime("%dth %B %y") %> at <%= @order.updated_at.time.strftime("%H:%M") %></p>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Product</th>
          <th td class="td-eye-order" scope="col">Price</th>
          <th td class="td-eye-order" scope="col">Quantity</th>
          <th td class="td-eye-order" scope="col">Subtotal</th>
        </tr>
      </thead>
      <tbody class="tbody-order">
              <% @order_items.includes([:product]).each do |order_item| %>
        <tr>
          <td>
            <%= link_to section_product_path(order_item.product.section_id, order_item.product_id), class:"text-decoration-none" do %>
              <%= cl_image_tag order_item.product.photo.key, height: 100, width: 100, crop: :fill, :effect=>"improve:outdoor" %>
            <% end %>
          </td>
          <td class="align-middle td-eye-order"><%= order_item.product.price %></td>
          <td class="align-middle td-eye-order"><%= order_item.quantity %></td>
          <td class="align-middle td-eye-order"><%= number_with_delimiter(order_item.total_price.to_i, delimiter: "’") %></td>
        </tr>
      <% end %>
      <% if @order.has_bag? %>
        <tr style="border-bottom: white;">
          <td>Option Cooler bag</td>
        </tr>
        <tr>
          <td>
            <img height="100" width="100" src="https://res.cloudinary.com/dyv1blw2a/image/upload/v1688311896/CoolerBag_wsqcfn.jpg">
          </td>
          <td class="align-middle td-eye-order">150</td>
          <td class="align-middle td-eye-order">1</td>
          <td class="align-middle td-eye-order">150</td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <p>Subotal : Rs <%= number_with_delimiter((@order.total_price.to_i - 75), delimiter: "’") %></p>
    <p>Delivery Fees : Rs 75</p>
    <p class="fs-3">Total : Rs <%= number_with_delimiter(@order.total_price.to_i, delimiter: "’") %></p>
  </div>

<% else %>
  <div class="container">
    <div class="row">
      <h4>Your order is on the way...</h4>
      <div class="col-6">
        <div class="messages chatroom-map">
          <div style="height: calc(75vh - 75px);"
              data-controller="map"
              data-map-markers-value="<%= @marker.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="chatroom"
          data-controller="chatroom-subscription"
          data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">
          <div class="messages" data-chatroom-subscription-target="messages">
            <% @order.chatroom.messages.each do |message| %>
              <%= render "messages/message", message: message %>
            <% end %>
          </div>
          <%= simple_form_for(@message, url: order_chatroom_messages_path(@order, @chatroom), method: :post, html: { autocomplete: 'off', data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" }) do |f| %>
            <%= f.input :content,
              label: false,
              placeholder: "Say something to Dennis",
              wrapper_html: {class: "flex-grow-1"}, html: {data: {action: "turbo:submit-end->chatroom-subscription#resetForm"}}
            %>
            <%= f.submit "Send", class: "btn btn-chat mb-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <p>Order was created on the <%= @order.created_at.strftime("%dth %B %y") %> at <%= @order.created_at.time.strftime("%H:%M") %></p>
    <table class="table">
      <thead>
        <tr>
          <th>Product</th>
          <th td class="td-eye-order" scope="col">Price</th>
          <th td class="td-eye-order" scope="col">Quantity</th>
          <th td class="td-eye-order" scope="col">Subtotal</th>
        </tr>
      </thead>
      <% @order_items.includes([:product]).each do |order_item| %>
        <tr>
          <td>
            <%= link_to section_product_path(order_item.product.section_id, order_item.product_id), class:"text-decoration-none" do %>
              <%= cl_image_tag order_item.product.photo.key, height: 100, width: 100, crop: :fill, :effect=>"improve:outdoor" %>
            <% end %>
          </td>
          <td class="align-middle td-eye-order"><%= order_item.product.price %></td>
          <td class="align-middle td-eye-order"><%= order_item.quantity %></td>
          <td class="align-middle td-eye-order"><%= number_with_delimiter(order_item.total_price.to_i, delimiter: "’") %></td>
        </tr>
      <% end %>
      <% if @order.has_bag? %>
        <tr style="border-bottom: white;">
          <td>Option Cooler bag</td>
        </tr>
        <tr>
          <td>
            <img height="100" width="100" src="https://res.cloudinary.com/dyv1blw2a/image/upload/v1688311896/CoolerBag_wsqcfn.jpg">
          </td>
          <td class="align-middle td-eye-order">150</td>
          <td class="align-middle td-eye-order">1</td>
          <td class="align-middle td-eye-order">150</td>
        </tr>
      <% end %>
    </table>
    <p>Subotal : Rs <%= number_with_delimiter((@order.total_price.to_i - 75), delimiter: "’") %></p>
    <p>Delivery Fees : Rs 75</p>
    <p class="fs-3">Total : Rs <%= number_with_delimiter(@order.total_price.to_i, delimiter: "’") %></p>
    <% if current_user.is_admin? %>
      <div class="row">
        <p clas="fs-2" style="text-align:left; color:red !important; text-decoration:underline;">ADMIN SECTION :</p>
        <div class="col-6">
          <div class="d-flex my-4">
            <%= simple_form_for(@order) do |f| %>
              <button class= "btn btn-success btn-sm"><%= f.button :submit, 'Delivered?' %></button>
            <% end %>
          <div class="ms-4">
            <%= link_to "delete order", order_path(@order), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this order?" } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>