config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sections#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sections, only: %i[index show] do
    resources :products, only: %i[show] do
      resources :ratings, only: %i[index new create]
    end
  end
  resources :products, only: %i[index]
  resources :orders, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[show new create]
    resources :chatrooms, only: :show do
      resources :messages, only: %i[new create]
    end
  end
  resource :cart, only: %i[show edit update]
  get "cart/confirmation", to: "carts#confirmation", as: :cart_confirmation
  resources :order_items, only: %i[new create edit update destroy]
  get "contact", to: "contact#show", as: :contact
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :section
  has_many :ratings
  has_one :order_item
  has_one_attached :photo

  validates :title, :price, presence: true

  acts_as_taggable_on :tags

  include PgSearch::Model

  pg_search_scope :global_search,
  against: [ :title, :description ],
  associated_against: {
    section: [ :title ],
    :tags => [:name]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_product, only: %i[show]

  def index
    @tags = ActsAsTaggableOn::Tag.all
    if params[:query].present?
      @products = Product.global_search(params[:query]).order(:title)
    else
      @products = Product.all.order(:title)
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "products/list", locals: {products: @products}, formats: [:html] }
    end
  end

  def show
    @order_item = OrderItem.new
    @ratings = Rating.all
    @sum_rates = []
    product_rating
    @user_rating = user_rating
    search
  end

  private

  def user_rating
    rating_user = []
    @product.ratings.each do |rating|
      rating_user << rating.user_id
    end
    rating_user
  end

  def show_star_rating(rating)
    zero_star_icon_name = "star"
    full_star_icon_name = "star_fill"
    half_star_icon_name = "star_lefthalf_fill"
    rating_round_point5 = (rating * 2).round / 2.0
    (1..5).map do |i|
      next(full_star_icon_name) if i <= rating_round_point5
      next(half_star_icon_name) if rating_round_point5 + 0.5 == i
      zero_star_icon_name
    end
  end

  def product_rating
    unless @product.ratings == []
      @product.ratings.each do |rating|
        @sum_rates << rating.rate
      end
      sum = 0
      @sum_rates.each do |sum_rate|
        sum += sum_rate
      end
      average = sum.to_f / @sum_rates.size
      @total_rate = show_star_rating(average)
    end
  end

  def set_product
    @section = Section.find(params[:section_id])
    @product = Product.find(params[:id])
  end

  def search
    if params[:query].present?
      redirect_to products_path(query: params[:query]) and return
    end
  end
end

app/views/products/_list.html.erb
<div class="cards" data-search-products-target="list">
  <% @products.each do |product| %>
    <% @section = product.section_id %>
    <%= link_to section_product_path(@section, product), class:"text-decoration-none" do %>
    <div class="card">
      <%= cl_image_tag product.photo.key, crop: :fill,  class:"cards-img"%>
      <div class="card-tags">
            <% product.tags.each do |tag| %>
              <h6><span><%= tag.name %></span></h6>
            <% end %>
      </div>
      <div class="card-body border-top border-secondary">
        <h6 class="card-title"><%= product.title %></h6>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/products/index.html.erb
<ul class="breadcrumb">
  <li><a href="/"><i class="fa-solid fa-house"></i></a></li>
  <li><a href="/products">Products</a></li>
</ul>
<div class="homepage">
  <div class="container py-1" data-controller="search-products">
    <div class="row justify-content-center py-2">
      <div class="col-sm-8 my-3">
        <%= form_with url: products_path, method: :get, class: "d-flex", data: {search_products_target: "form"}, html: { autocomplete: 'off' } do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "ki to p roder ?",
                data: {action: "keyup->search-products#update",
                search_products_target: "input"}
          %>
          <%= submit_tag "Search", name: "", class: "btn btn-search form-button" %>
        <% end %>
      </div>
    </div>
    <div class="row justify-content-center tag-list py-3">
      <% @tags.each do |tag| %>
        <a class="text-center btn-tag2" style="text-align: center" href="/products?query= <%= tag.name %>"><%= tag.name %></a>
      <% end %>
    </div>
    <p class="pb-4 fs-3 pt-2">Products</p>
    <%= render "list", products: @products %>
  </div>
</div>

app/views/products/show.html.erb
<ul class="breadcrumb">
  <li><a href="/"><i class="fa-solid fa-house"></i></a></li>
  <li><a href="/sections/<%= @section.id %>"><%= @section.title %></a></li>
  <li><a href="/sections/<%= @section.id %>/products/<%= @product.id %>"><%= @product.title %></a></li>
</ul>
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mb-5 card" id="product-card-show">
      <%= cl_image_tag @product.photo.key, height: 500, width: 500, crop: :fill %>
      <div class="img-tags">
        <% @product.tags.each do |tag| %>
          <span><%= tag.name %></span>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div>
        <H2><%= @product.title %></H2>
        <H3>
          <% if @product.ratings == [] %>
            <div class="container p-0">
              <div class="row">
                <div class="col-5">
                  <i class="fa-regular fa-star" style="color: #ffde0a;"></i>
                  <i class="fa-regular fa-star" style="color: #ffde0a;"></i>
                  <i class="fa-regular fa-star" style="color: #ffde0a;"></i>
                  <i class="fa-regular fa-star" style="color: #ffde0a;"></i>
                  <i class="fa-regular fa-star" style="color: #ffde0a;"></i>
                </div>
                <div class="col-6">
                  <H2 class="fs-6">*No rating yet</H2>
                  <% if user_signed_in? %>
                    <%= link_to new_section_product_rating_path(@section, @product), class:"text-decoration-none ", data: { controller: 'turbo' } do %>
                      <h2 class="fs-6 btn-rating">add a rating</i></h2>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% else %>
            <div class="container p-0">
              <div class="row">
                <div class="col-5">
                  <% @total_rate.each do |star| %>
                    <% if star == "star_fill" %>
                      <i class="fa-solid fa-star" style="color: #ffde0a;"></i>
                    <% elsif star == "star_lefthalf_fill" %>
                      <i class="fa-solid fa-star-half-stroke" style="color: #ffde0a;"></i>
                    <% else star %>
                      <i class="fa-regular fa-star" style="color: #ffde0a;"></i>
                    <% end %>
                  <% end %>
                </div>
                <div class="col-4 p-0 m-0">
                  <% if @sum_rates.size == 1 %>
                    <H2 class="fs-6"><%= @sum_rates.size + 58 %> ratings</H2>
                  <% else %>
                    <H2 class="fs-6"><%= @sum_rates.size * 59 %> ratings</H2>
                  <% end %>
                  <% unless user_signed_in? && @user_rating.include?(current_user.id) %>
                    <% if user_signed_in? %>
                      <%= link_to new_section_product_rating_path(@section, @product), class:"text-decoration-none ", data: { controller: 'turbo' } do %>
                        <h2 class="fs-6 btn-rating">add a rating</i></h2>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </H3>
        <div class="mt-4">
          <p style="font-weight: 600 !important;">Description :</p>
          <p><%= @product.description %></p>
        </div>
        <div class="mt-2">
          <p>
            <strong style="font-weight: 600 !important;">Prix :</strong> Rs <%= number_with_delimiter(@product.price, delimiter: "’")  %>
          </p>
        </div>
        <% if @product.quantity == 0 %>
          <div class="mt-2">
            <p>
              <strong style="font-weight: 600 !important; color: #EB5757 !important;">Out of stock</strong>
            </p>
          </div>
        <% elsif @product.quantity < 10 %>
          <div class="mt-2">
            <% if @product.quantity == 1 %>
              <p>
                <strong style="font-weight: 600 !important; color: #EB5757 !important;">Only <%= @product.quantity %> product left!</strong>
              </p>
            <% else %>
              <p>
                <strong style="font-weight: 600 !important; color: #EB5757 !important;">Only <%= @product.quantity %> products left!</strong>
              </p>
            <% end %>
          </div>
          <div class="mt-2" data-controller="order-item" data-order-item-price-value=<%= @product.price %>>
            <%= simple_form_for(@order_item, url: order_items_path(@product), method: :post) do |f| %>
              <%= f.input :quantity, input_html: { value: 1, min: 1, max: @product.quantity, step: 1, data: {order_item_target: "quantity", action: "change->order-item#test"} }, label: 'Quantity' %>
              <%= f.input :total_price, label: 'Total Price', input_html: { value: @product.price , data: {order_item_target: "totalprice"}, readonly: true} %>
              <%= f.hidden_field :section_id, value: @section.id %>
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.hidden_field :cart_id, value: @cart.id %>
              <%= f.button :submit, 'Add to Cart', class: "btn-outline-cart" %>
            <% end %>
          </div>
        <% else %>
          <div class="mt-2" data-controller="order-item" data-order-item-price-value=<%= @product.price %>>
            <%= simple_form_for(@order_item, url: order_items_path(@product), method: :post) do |f| %>
              <%= f.input :quantity, input_html: { value: 1, min: 1, step: 1, data: {order_item_target: "quantity", action: "change->order-item#test"} }, label: 'Quantity', class: "form-product" %>
              <%= f.input :total_price, label: 'Total Price', input_html: { value: @product.price , data: {order_item_target: "totalprice"}, readonly: true} %>
              <%= f.hidden_field :section_id, value: @section.id %>
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.hidden_field :cart_id, value: @cart.id %>
              <%= f.button :submit, 'Add to Cart', class: "btn-outline-cart" %>
            <% end %>
          </div>
        <% end  %>
      </div>
    </div>
  </div>
</div>